version: "3"
services:
  plan:
    image: hashicorp/terraform:0.11.13
    network_mode: host
    ports:
      - 3306:3306
    volumes:
      - .:/workdir
    working_dir: /workdir
    entrypoint: sh
    command: -c "scripts/plan.sh"

  apply:
    image: hashicorp/terraform:0.11.13
    network_mode: host
    ports:
      - 3306:3306
    volumes:
      - .:/workdir
    working_dir: /workdir
    entrypoint: sh
    command: -c "scripts/apply.sh"
